version: '3.6'

services:
  user-service:
    image: vaishali007/user-microservice:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oblf
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
