import { INestApplication } from "@nestjs/common";
import request from "supertest";
import { v4 as uuidv4 } from "uuid"; // To generate unique IDs for testing
import { createTestApp, withTenant } from "../utils/app.factory";
import { loginAndGetToken, authHeaderFromToken } from "../utils/auth.helper";

jest.setTimeout(20000);
function logRes(label: string, res: request.Response, expected?: number[] | number) {
  try {
    const body = JSON.stringify(res.body);
    const trimmed = body && body.length > 1200 ? body.slice(0, 1200) + "…(truncated)" : body;
    // eslint-disable-next-line no-console
    console.log(
      JSON.stringify(
        { label, status: res.status, expected, body: trimmed ? JSON.parse(trimmed) : undefined },
        null,
        2
      )
    );
  } catch {
    // eslint-disable-next-line no-console
    console.log(`[e2e][${label}] status=${res.status} (body not JSON)`);
  }
}
// --- Mock Data ---
// Use a fixed mock tenant ID for the withTenant helper
const MOCK_TENANT_ID = "test-tenant-12345"; 
const MOCK_ROLE_ID = "test-role-98765";

// Payload for creating a new privilege
const MOCK_CREATE_PRIVILEGE_DTO = {
  name: "TEST_PRIVILEGE_E2E",
  description: "E2E Test Privilege Description",
  // Add other required fields based on your CreatePrivilegesDto
  resource: "TEST_RESOURCE",
  action: "READ",
};
// -----------------


describe("RBAC Privileges (e2e)", () => {
  let app: INestApplication;
  let token: string | undefined;
  let createdPrivilegeId: string; // Variable to store the ID for follow-up tests

  // --- Setup and Teardown ---

  beforeAll(async () => {
    app = await createTestApp();
    token = (await loginAndGetToken(app))?.access_token;

    if (!token) {
        throw new Error("Failed to get authentication token.");
    }
    // Pre-create a privilege for subsequent GET/DELETE tests
    const preCreate = await request(app.getHttpServer())
      .post("/rbac/privileges/create")
      .set(withTenant(authHeaderFromToken(token)))
      .send({ privileges: [{ title: "E2E Privilege", code: `e2e_${Date.now()}` }] });
    logRes("PRE CREATE /rbac/privileges/create", preCreate, [200, 201]);
    expect([200, 201]).toContain(preCreate.status);
    const created = preCreate.body?.result?.privileges?.[0];
    if (!created?.privilegeId) {
      throw new Error(`Pre-create did not return privilegeId: ${JSON.stringify(preCreate.body)}`);
    }
    createdPrivilegeId = created.privilegeId;
    // eslint-disable-next-line no-console
    console.log(`[e2e] pre-created privilegeId=${createdPrivilegeId}`);
  });

  afterAll(async () => {
    await app.close();
  });

  // --- GET /rbac/privileges (List Endpoint) ---

  it("GET /rbac/privileges returns 200 with required query params", async () => {
    // FIX: The controller's @Get() handler requires tenantId and roleId queries.
    const res = await request(app.getHttpServer())
      .get(`/rbac/privileges?tenantId=${MOCK_TENANT_ID}&roleId=${MOCK_ROLE_ID}`) // <-- FIXED LINE
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expect 200 (OK) or 204 (No Content)
    logRes("GET /rbac/privileges?tenantId&roleId", res, [200, 204]);
    expect([200, 204]).toContain(res.status); 
  });

  // --- POST /rbac/privileges/create (Create Endpoint) ---

  // Re-enable the POST test and use it to set up the necessary data
  describe("POST /rbac/privileges/create", () => {
    it("should create privilege (201) and store its ID", async () => {
      const res = await request(app.getHttpServer())
        .post("/rbac/privileges/create")
        .set(withTenant(authHeaderFromToken(token)))
        .send(MOCK_CREATE_PRIVILEGE_DTO);
        
      // Expect 201 (Created)
      logRes("POST /rbac/privileges/create", res, [200, 201]);
      expect([200, 201]).toContain(res.status); 
      
      const newOne = res.body?.result?.privileges?.[0]?.privilegeId;
      // Do not overwrite createdPrivilegeId used by subsequent tests; just log
      // eslint-disable-next-line no-console
      console.log(`[e2e] created extra privilege id=${newOne || "N/A"}`);
    });
  });

  // --- GET /rbac/privileges/:privilegeId (Retrieve Endpoints) ---

  it("GET /rbac/privileges/:privilegeId with valid id returns 200", async () => {
    // Use the ID generated by the previous POST test
    const res = await request(app.getHttpServer())
      .get(`/rbac/privileges/${createdPrivilegeId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    logRes(`GET /rbac/privileges/${createdPrivilegeId}`, res, 200);
    expect(res.status).toBe(200);
    expect(res.body?.result?.privilegeId).toBe(createdPrivilegeId);
  });

  it("GET /rbac/privileges/:privilegeId invalid id returns 400/404", async () => {
    const res = await request(app.getHttpServer())
      .get("/rbac/privileges/not-a-uuid")
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expected to fail validation (400) or not found (404)
    logRes("GET /rbac/privileges/not-a-uuid", res, [400, 404]);
    expect([400, 404]).toContain(res.status);
  });
  
  it("GET /rbac/privileges/:privilegeId non-existent id returns 404", async () => {
    const nonExistentId = uuidv4(); // A valid UUID that shouldn't exist
    const res = await request(app.getHttpServer())
      .get(`/rbac/privileges/${nonExistentId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    logRes(`GET /rbac/privileges/${nonExistentId}`, res, 404);
    expect(res.status).toBe(404);
  });

  // --- DELETE /rbac/privileges/:privilegeId (Delete Endpoints) ---

  it("DELETE /rbac/privileges/:privilegeId with invalid id returns 400/404", async () => {
    const res = await request(app.getHttpServer())
      .delete("/rbac/privileges/not-a-uuid")
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expected to fail validation (400) or not found (404)
    logRes("DELETE /rbac/privileges/not-a-uuid", res, [400, 404]);
    expect([400, 404]).toContain(res.status);
  });

  it("DELETE /rbac/privileges/:privilegeId with valid id returns 200/204", async () => {
    // Use the ID generated by the POST test to clean up
    const res = await request(app.getHttpServer())
      .delete(`/rbac/privileges/${createdPrivilegeId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expect 200 (OK) or 204 (No Content)
    logRes(`DELETE /rbac/privileges/${createdPrivilegeId}`, res, [200, 204]);
    expect([200, 204]).toContain(res.status);
  });
  
  it("DELETE /rbac/privileges/:privilegeId (after deletion) returns 404", async () => {
    // Attempt to delete the same ID again; it should no longer exist
    const res = await request(app.getHttpServer())
      .delete(`/rbac/privileges/${createdPrivilegeId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    logRes(`DELETE-again /rbac/privileges/${createdPrivilegeId}`, res, 404);
    expect(res.status).toBe(404);
  });
});