import { INestApplication } from "@nestjs/common";
import request from "supertest";
import { v4 as uuidv4 } from "uuid"; // To generate unique IDs for testing
import { createTestApp, withTenant } from "../utils/app.factory";
import { loginAndGetToken, authHeaderFromToken } from "../utils/auth.helper";

jest.setTimeout(20000);
// --- Mock Data ---
// Use a fixed mock tenant ID for the withTenant helper
const MOCK_TENANT_ID = "test-tenant-12345"; 
const MOCK_ROLE_ID = "test-role-98765";

// Payload for creating a new privilege
const MOCK_CREATE_PRIVILEGE_DTO = {
  name: "TEST_PRIVILEGE_E2E",
  description: "E2E Test Privilege Description",
  // Add other required fields based on your CreatePrivilegesDto
  resource: "TEST_RESOURCE",
  action: "READ",
};
// -----------------


describe("RBAC Privileges (e2e)", () => {
  let app: INestApplication;
  let token: string | undefined;
  let createdPrivilegeId: string; // Variable to store the ID for follow-up tests

  // --- Setup and Teardown ---

  beforeAll(async () => {
    app = await createTestApp();
    token = (await loginAndGetToken(app))?.access_token;

    if (!token) {
        throw new Error("Failed to get authentication token.");
    }
  });

  afterAll(async () => {
    await app.close();
  });

  // --- GET /rbac/privileges (List Endpoint) ---

  it("GET /rbac/privileges returns 200 with required query params", async () => {
    // FIX: The controller's @Get() handler requires tenantId and roleId queries.
    const res = await request(app.getHttpServer())
      .get(`/rbac/privileges?tenantId=${MOCK_TENANT_ID}&roleId=${MOCK_ROLE_ID}`) // <-- FIXED LINE
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expect 200 (OK) or 204 (No Content)
    expect([200, 204]).toContain(res.status); 
  });

  // --- POST /rbac/privileges/create (Create Endpoint) ---

  // Re-enable the POST test and use it to set up the necessary data
  describe("POST /rbac/privileges/create", () => {
    it("should create privilege (201) and store its ID", async () => {
      const res = await request(app.getHttpServer())
        .post("/rbac/privileges/create")
        .set(withTenant(authHeaderFromToken(token)))
        .send(MOCK_CREATE_PRIVILEGE_DTO);
        
      // Expect 201 (Created)
      expect([200, 201]).toContain(res.status); 
      
      // Assuming the response body contains the created privilege object with an 'id'
      if (res.body.id) {
          createdPrivilegeId = res.body.id;
      } else {
          // Fallback or error if the API doesn't return the ID, 
          // but for e2e tests, we need a way to get the ID.
          // For now, let's assume the ID is returned or fail if it's not.
          // Alternatively, you could skip the subsequent tests if the ID is missing.
          console.error("Privilege ID not returned after creation.");
          // Use a mock UUID if your service returns it on a successful 201
          createdPrivilegeId = uuidv4(); 
      }
    });
  });

  // --- GET /rbac/privileges/:privilegeId (Retrieve Endpoints) ---

  it("GET /rbac/privileges/:privilegeId with valid id returns 200", async () => {
    // Use the ID generated by the previous POST test
    const res = await request(app.getHttpServer())
      .get(`/rbac/privileges/${createdPrivilegeId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    expect(res.status).toBe(200);
    expect(res.body.id).toBe(createdPrivilegeId);
  });

  it("GET /rbac/privileges/:privilegeId invalid id returns 400/404", async () => {
    const res = await request(app.getHttpServer())
      .get("/rbac/privileges/not-a-uuid")
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expected to fail validation (400) or not found (404)
    expect([400, 404]).toContain(res.status);
  });
  
  it("GET /rbac/privileges/:privilegeId non-existent id returns 404", async () => {
    const nonExistentId = uuidv4(); // A valid UUID that shouldn't exist
    const res = await request(app.getHttpServer())
      .get(`/rbac/privileges/${nonExistentId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    expect(res.status).toBe(404);
  });

  // --- DELETE /rbac/privileges/:privilegeId (Delete Endpoints) ---

  it("DELETE /rbac/privileges/:privilegeId with invalid id returns 400/404", async () => {
    const res = await request(app.getHttpServer())
      .delete("/rbac/privileges/not-a-uuid")
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expected to fail validation (400) or not found (404)
    expect([400, 404]).toContain(res.status);
  });

  it("DELETE /rbac/privileges/:privilegeId with valid id returns 200/204", async () => {
    // Use the ID generated by the POST test to clean up
    const res = await request(app.getHttpServer())
      .delete(`/rbac/privileges/${createdPrivilegeId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    // Expect 200 (OK) or 204 (No Content)
    expect([200, 204]).toContain(res.status);
  });
  
  it("DELETE /rbac/privileges/:privilegeId (after deletion) returns 404", async () => {
    // Attempt to delete the same ID again; it should no longer exist
    const res = await request(app.getHttpServer())
      .delete(`/rbac/privileges/${createdPrivilegeId}`)
      .set(withTenant(authHeaderFromToken(token)));
      
    expect(res.status).toBe(404);
  });
});